<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160305150025 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE dropesoft_trainingday_domain_model_trainingday (persistence_object_identifier VARCHAR(40) NOT NULL, trainingplan VARCHAR(40) DEFAULT NULL, day INT NOT NULL, week INT NOT NULL, period INT NOT NULL, description LONGTEXT DEFAULT NULL, executed TINYINT(1) DEFAULT '0', note VARCHAR(255) DEFAULT NULL, dateexecute DATETIME DEFAULT NULL, type INT NOT NULL, INDEX IDX_2071D0BD7002AD59 (trainingplan), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET latin1");
		$this->addSql("CREATE TABLE dropesoft_trainingday_domain_model_trainingplan (persistence_object_identifier VARCHAR(40) NOT NULL, app VARCHAR(40) DEFAULT NULL, title VARCHAR(150) NOT NULL, disable TINYINT(1) DEFAULT '0', note VARCHAR(255) DEFAULT NULL, INDEX IDX_9840D6F1C96E70CF (app), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET latin1");
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingday ADD CONSTRAINT FK_2071D0BD7002AD59 FOREIGN KEY (trainingplan) REFERENCES dropesoft_trainingday_domain_model_trainingplan (persistence_object_identifier)");
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingplan ADD CONSTRAINT FK_9840D6F1C96E70CF FOREIGN KEY (app) REFERENCES posit_marketplace_domain_model_app (persistence_object_identifier)");
}	
	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingday DROP FOREIGN KEY FK_2071D0BD7002AD59");
		$this->addSql("DROP TABLE dropesoft_trainingday_domain_model_trainingday");
		$this->addSql("DROP TABLE dropesoft_trainingday_domain_model_trainingplan");
	}
}
