<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160306182413 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingplan ADD owner VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingplan ADD CONSTRAINT FK_9840D6F1CF60E67C FOREIGN KEY (owner) REFERENCES posit_intranet_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_9840D6F1CF60E67C ON dropesoft_trainingday_domain_model_trainingplan (owner)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingplan DROP FOREIGN KEY FK_9840D6F1CF60E67C");
		$this->addSql("DROP INDEX IDX_9840D6F1CF60E67C ON dropesoft_trainingday_domain_model_trainingplan");
		$this->addSql("ALTER TABLE dropesoft_trainingday_domain_model_trainingplan DROP owner");
	}
}
